export class Actions {
    UI__SELECT_NAV_ITEM: string = 'UI__SELECT_NAV_ITEM';
    UI__TOGGLE_SIDEBAR_VIEW: string = 'UI__TOGGLE_SIDEBAR_VIEW';
    UI__SET_DEGREE_UNIT: string = 'UI__SET_DEGREE_UNIT';
    UI__TOGGLE_DARK_MODE: string = 'UI__TOGGLE_DARK_MODE';
    CHOOSE_LOCATION: string = 'CHOOSE_LOCATION';
    GET_GEO_LOCATION: string = 'GET_GEO_LOCATION';
    GET_CURRENT_WEATHER: string = 'GET_CURRENT_WEATHER';
    GET_FORECAST: string = 'GET_FORECAST';
    GET_FAVORITES: string = 'GET_FAVORITES';
    UPDATE_FAVORITES: string = 'UPDATE_FAVORITES';
    SEARCH_LOCATION: string = 'SEARCH_LOCATION';
    GET_REQUEST_STATUS: string = 'GET_REQUEST_STATUS';
}