export class Actions {
    SET_DEGREE_UNIT: string = 'SET_DEGREE_UNIT';
    GET_SEARCH_QUERY: string = 'GET_SEARCH_QUERY';
    GET_CURRENT_WEATHER: string = 'GET_CURRENT_WEATHER';
    GET_FORECAST: string = 'GET_FORECAST';
    GET_FAVORITES: string = 'GET_FAVORITES';
    ADD_TO_FAVORITES: string = 'ADD_TO_FAVORITES';
    SEARCH_LOCATION: string = 'SEARCH_LOCATION';
    GET_REQUEST_STATUS: string = 'GET_REQUEST_STATUS';
}